export type TEnvVars =
  | 'DISCORD_DEVELOPMENT_BOT_TOKEN'
  | 'DISCORD_PRODUCTION_BOT_TOKEN'
  | 'NODE_ENV'
  | 'DATABASE_ARGS'
  | 'DATABASE_HOST'
  | 'DATABASE_USER'
  | 'DATABASE_PASSWORD'
  | 'DATABASE_SCHEMA';
